import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Link from 'next/link';
import { signIn, signOut, useSession } from "next-auth/client"


export default function Home() {

  const [session, loading] = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {!session && (
          <>
            Not Signed in <br/>
            <button onClick={signIn}>Sign in</button>
          </>
        )}
        {session && (
          <>
            Signed in <br/>
            User: {session.user.name} <br/>
            <button onClick={signOut}>Sign out</button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <p>Next Auth Example</p>
      </footer>
    </div>
  )
}
